project:
  type: book
  output-dir: docs

book:
  title: "Wirtschaftlicher Wandel und Global Givernance"
  author: "Prof. Dr. Jan S. Voßwinkel"
  # date: "2024"
  subtitle: "Sommersemester 2025"
  #lang: de
  language:  _language.yml
  repo-url: https://github.com/janvoss/wwgg.git
#  issued: "Sommersemester 2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Phänomenologie.qmd
    - Ioe.qmd # Institutionenökonomik
    - Geschichte.qmd # die Revolutionen?
    - Treiber.qmd # Treiber des Wandels, Schumpeter, Boyer, Alston, ...?
    - Spieltheorie.qmd # Evolution?
    - Governance.qmd
    - literatur.qmd
    - Uebungsfragen.qmd

bibliography: wwgg.bib
#csl: dresden.csl #Ohne funktioniert es gut, mit nicht. 
# Aber warum? Und was ist mit Herausgeberwerken (Hrsg vs. Ed?)


format:
  html:
    theme: cosmo
    code-fold: true
    code-overflow: wrap

editor: source