# Global Governance

## Begriff Global Governance

::: {.callout-note title='Definition Governance'}

Die Gesamtheit der **kollektiven Regelungen**, die auf eine **bestimmte Problemlage** oder einen bestimmten gesellschaftlichen Sachverhalt zielen und mit Verweis auf das **Kollektivinteresse** der betroffenen Gruppe gerechtfertigt werden (@simonis_global_2022 nach Zürn (2008)).

:::

```{python}
#| message: false
#| warning: false
#| fig-cap: "nach @simonis_global_2022"

from graphviz import Source
from IPython.display import display

dot = '''
digraph G {
    rankdir=TD;
    node [shape=plaintext, width=3];
    edge [style=invis];

    subgraph cluster_0 {
        label = "Global Governance";
        labelloc = "t";
        fontsize = 18;
        style = "filled,rounded";
        color = "lightblue";

        // Cluster 1
        subgraph cluster_1 {
            label = "Governance";
            labelloc = "t";
            { a1 -> a2 -> a3; }
            a1 [label="vs. regieren:\l verschiedene Akteure\l"];
            a2 [label="vs. managen:\l nicht nach innen gerichtet\l"];
            a3 [label = "Merkmale:\l - Problemorientierung\l -Maßnahmenorientierung\l - Bindewirkung\l -Rechtfertigungszwang\l  (-orientierung)\l"];
        }

        // Cluster 2
        subgraph cluster_2 {
            label = "Global";
            labelloc = "t";
            penwidth = 1;
            {b1 -> b2 -> b3 -> b4; }
            b1 [label="Weltumspannende Probleme\\l"];
            b2 [label="lokale Probleme mit\\l globaler Normativität\\l"];
            b3 [label="Funktionsbedingungen\l globaler Vernetzung\\l"];
            b4 [label="Anerkennung des Prinzips\l der Staatlichkeit\l"]
        }
    }
}
'''

src = Source(dot, format="svg")
display(src)
```

::: {.callout-note title='Definition Global Governance'}

Global Governance bezeichnet als an der Sicherung und Gewährleistung von globalen öffentlichen Gütern orientiertes, auf Legitimation bedachtes, (problemlösendes) Handeln von überstaatlichen öffentlichen, privaten und hybriden Institutionen und der im Rahmen dieser Institutionen handelnden Personen und Organisationen. 

Politische Aktivitäten, die zum Aufbau neuer Institutionen/Organisationen der Gloabel Governance führen sollen, werden als vorbereitende Global Governance mit unter das Konzept subsummiert [@simonis_global_2022].

:::

```{python}
#| message: false
#| warning: false

import graphviz
from IPython.display import display

g = graphviz.Digraph('satelliten', engine='circo')

# Zentrum mit spezieller Farbe
g.node('Zentrum', 'Global Governance',
       fontsize='20',
       fontname='Times-Bold',
       shape='circle',
       width='3',
       style='filled',
       fillcolor='#00BFFF')

# Satelliten-Knoten mit Farbe #00FFFF
satellites = [
    ('A', 'Regieren ohne Regierung'),
    ('B', 'Staatliche Akteure'),
    ('C', 'Nichtstaatliche Akteure'),
    ('D', 'Grenzüberschreitende/ globale Probleme'),
    ('E', 'Völkerrecht'),
    ('F', 'informelle Vereinbarungen')
]

for node_id, label in satellites:
    g.node(node_id, label, style='filled', fillcolor='#00FFFF', penwidth='1')

# Verbindungen zum Zentrum
g.edges([(node_id, 'Zentrum') for node_id, _ in satellites])

display(g)
```



## Begriff Globalisierung

::: {.callout-note title='Globalisierung'}

**Globalisierung**

- **Internationalisierung**  
  (mehr Handel, und zwischenstaatliche Interdependenz)

- **Liberalisierung**  
  (Auflösung regulativer Hemmnisse)

- **Universalisierung/Westernisierung**  
  (Angleichung von Werten/ Angleichung *auf* westliche Werte)

- **Deterritorialisierung**  
  (räumliche und zeitliche Verdichtung des Globalen)
 [@glaab_globalisierung_2024 nach Scholte(2000)].

:::

## Dynamiken im Innen- und Außenverhältnis

```{python}
#| message: false
#| warning: false
#| fig-cap: Globale Dynamiken in Innen- und Außenverhältnissen

from graphviz import Digraph
from IPython.display import display

dot = Digraph()
dot.attr(rankdir='LR')

# Gleiche Breite und kein Rand für alle Knoten
dot.node_attr.update(width='1.8', fixedsize='true', penwidth='0')

with dot.subgraph(name='cluster_1') as c1:
    c1.attr(rank='same', style="rounded",
            label='Außenverhältnis',
            fontname='Times-Bold')
   
    c1.node('A1', 'Entflechtung')
    c1.node('B1', 'Blockbildung')
   
    c1.node('A', 'Globalisierung')
    c1.node('B', 'Global Governance')
   

with dot.subgraph(name='cluster_2') as c2:
    c2.attr(rank='same', style="rounded",
            label="Innenverhältnis",
            fontname='Times-Bold')
    c2.node('C1', 'Autokratisierung')
    c2.node('D1', 'Polarisierung')
    
    c2.node('C', 'Demokratisierung')
    c2.node('D', 'Liberalisierung')
    

dot.edge('A', 'B', style='invis')
dot.edge('A1', 'B1', style='invis')
dot.edge('C', 'D', style='invis')
dot.edge('C1', 'D1', style='invis')

dot.edge('A', 'A1', constraint='false')
dot.edge('B', 'B1', constraint='false')

dot.edge('C', 'C1', constraint='false')
dot.edge('D', 'D1', constraint='false')


# print(dot)

display(dot)
```

## Formen der internationalen Koordination

```{python}
#| message: false
#| warning: false
#| fig-cap: Formen der internationalen Koordination nach @patrick_rules_2023

# 4 Modelle nach Stewart Patrick

from graphviz import Digraph
from IPython.display import display

dot = Digraph()

# Layout des gesamten Graphen
dot.attr(rankdir='LR')

# Funktion zur Erstellung eines Clusters mit standardisierten Knoten und Auffüllen mit Platzhaltern
def create_cluster(dot, name, label, color, fillcolor, nodes, max_nodes):
    with dot.subgraph(name=name) as c:
        c.attr(label=label,
               fontname="times-bold",
               style='filled,rounded',
               fillcolor=fillcolor,
               color=color,
               penwidth='1.5')

        # Standardknoten hinzufügen
        for node_id, node_label in nodes:
            c.node(node_id, node_label, width="3.2", height="1", shape='none')  # Einheitliche Breite und Höhe


        # Unsichtbare Platzhalterknoten hinzufügen
        for i in range(len(nodes), max_nodes):
            c.node(f'{name}_placeholder_{i}', '', style='invis', width="3.2", height="1")


# Clusterdefinitionen
clusters = [
    ('cluster_charta', 'Charter-Modell', '#0000ff', '#0000ff90', [
        ('a1', 'Zusammenarbeit innerhalb der VN'),
        ('a2', 'Gleichrangigkeit der Staaten'),
        ('a3', 'Legitimität')
    ]),
    ('cluster_club', 'Club-Modell', '#0000ff', '#0000ff70', [
        ('b1', 'Zusammenarbeit Gleichgesinnter'),
        ('b2', 'NATO, OECD, BRICS'),
        ('b3', 'Solidarität')
    ]),
    ('cluster_konzert', 'Konzert-Modell', '#0000ff', '#0000ff50', [
        ('c1', 'Großmächte sprechen sich ab'),
        ('c2', 'Koexistenz unterschiedlicher\n Regierungstypen\n'),
        ('c3', 'Fähigkeit')
    ]),
    ('cluster_koalitionen', 'Koalitionen-Modell', '#0000ff', '#0000ff30', [
        ('d1', 'Ad hoc Zusammenarbeit'),
        ('d2', 'Sutuationsbedingte Kooperation'),
        ('d3', 'Flexibilität')
    ])
]

# Maximale Anzahl von Knoten in einem Cluster berechnen
max_nodes = max(len(cluster[4]) for cluster in clusters)

# Cluster erstellen
for name, label, color, fillcolor, nodes in clusters:
    create_cluster(dot, name, label, color, fillcolor, nodes, max_nodes)

# Unsichtbare Kanten für vertikale Anordnung zwischen den Clustern
dot.edge('a1', 'b1', style='invis')
dot.edge('b1', 'c1', style='invis')
dot.edge('c1', 'd1', style='invis')

# Ausgabe
display(dot)
```

