# Institutionenökonomik 

## Institutionenbegriff

[Hier auch Aokis doppelte Natur von Institutionen: Beschränkung und Freiheit durch Erwartungssicherheit]::

Institution

- Regelkomponente

- Überwachungskomponente

```{r Regeln, echo=F, message=F, warning=F, cache=F}

library(tidyverse)

df <- data.frame(Regel=c("Konvention", "Ethische Regel", "Sitte", "Formelle private Regel", "Regel positiven Rechts"),
                 "Überwachung" = c("Selbstüberwachung", "imperative Selbstbindung","informelle Überwachung durch andere Akteure", "organisierte private Überwachung", "organisierte staatliche Überwachung"),
                 'Institutionenkategorie'= c("intern vom Typ 1", "intern vom Typ 2",
                                             "intern vom Typ 3", "intern vom Typ 4",
                                             "extern"),
                 'Beispiel'=c("Regeln der Sprache", "Kategorischer Imperativ, privater Trainingsplan", "gesellschaftliche Umgangsformen", "Regeln des Sports", "Privat- und Strafrecht, öffentliches Recht"))


library(knitr)
# library(kableExtra)
kable(df) #%>% 
  #kable_styling(#bootstrap_options = c("responsive")
   # )

```

## Verhältnis von Institutionen zueinander

### Substitutives Verhältnis 

Der gleiche Zweck kann durch verschiedene (Arten von) Informationen erreicht werden.

Beispiele? 

### Komplementäres Verhältnis

[Isogai 2024]::

Eine Institution hat eine stärkere Regelungswirkung, wenn eine (passende) zweite Institution ebenfalls vorhanden ist.

$$F(x_1, y_1) - F(x_2, y_1) \geq F(x_1, y_2) - F(x_2, y_2)$$

$\Rightarrow$ Institutioneller log-in Effekt möglich.

Beispiele?

### Konfligierendes Verhältnis 

Es ist nicht möglich zwei bestimmte Institutionen gleichzeitig zu befolgen. 

Beispiele?

### Neutrales Verhältnis

Zwei Institutionen sind völlig unabhängig voneinander.

Beispiele?

## Zur Änderbarkeit von Institutionen: Erste Überlegungen 

## Konstitutionenökonomik

Grundidee: Rationale Individuen können sich einstimmig auf gute Regeln einigen.

Aber Eigeninteresse blockiert bei Interessenheterogenität evtl. Konsens.

Lösungsidee: Schleier des Nichtwissens. Individuen haben (zutreffendes) Wissen über positive Eigenschaften der Welt, aber kein Wissen über individuelle Charakteristika (oder abstrahieren davon).