---
editor: 
  markdown: 
    wrap: 72
---

# Übungsfragen {.unnumbered}

1.  Systematisieren Sie unterschiedliche Formen von Institutionen anhand
    der Art der Überwachung der Regeleinhaltung.

2.  In welchem Verhältnis können Institutionen zueinander stehen? Nennen
    Sie Beispiele.

3.  Erläutern Sie das Modell des sozialvertraglichen Konsenses hinter
    dem ,,Schleier des Nichtwissens". Welche Voraussetzungen müssen für
    einen solchen Konsens gegeben sein? Welchen Wert zur Erklärung der
    Institutionenentstehung messen Sie dieser Vorstellung bei?

4.  Erläutern Sie kurz die folgenden "Revolutionen": kognitive,
    neolithische, wissenschaftliche, industrielle und digitale
    Revolution.

5.  Erläutern Sie wissenschaftliche und wirtschaftliche Anreize für
    Innovationen.

6.  Charakterisieren Sie die gesellschaftliche Wirkung von Innovationen.

7.  Erläutern Sie den Innovationsprozess innerhalb eines gegebenen
    Paradigmas. Wodurch wird ein Paradigmenwechsel begünstigt?

8.  Erläutern Sie für verschiedene Arten von Regeln, wodurch
    institutioneller Wandel jeweils ausgelöst/begünstigt werden kann.

9.  Welche Rolle spielen mach Blyth Ideen im Prozess des
    institutionellen Wandels?

10. Welche Rolle spielen in diesem Zusammenhang Heuristiken?

11. Erläutern Sie den ,,Nietzscheanischen" Ausgangszustand nach
    A. L. Hillman. Wer kann in diesem Modell zur
    Institutionenentwicklung beitragen? Wovon hängt es ab, ob eine
    Gesellschaft in diesem Modell ,,befriedet" wird? Lohnen sich
    Produktivitätssteigerungen immer für alle Teile der Bevölkerung?

12. Erläutern Sie, was unter einem Nash-Gleichgewicht in reinen
    Strategien und was unter einem Nash-Gleichgewicht in gemischten
    Strategien zu verstehen ist.

13. Nach welchem Kalkül werden Strategien beim Spielen in gemischten
    Strategien gemischt?

14. Erläutern Sie, unter welchen Bedingungen der Anarchiezustand im
    Modell befriedet werden kann.

15. Inwiefern begegnen sich Staaten untereinander in einem
    ,,anarchischen" Umfeld? Wodurch wird der anarchische Charkater
    heutzutage eingehegt?

16. Was ist evolutionäre Spieltheorie?

17. Wodurch ist in diesem Zusammenhang ein Moran-Prozess gekennzeichnet?

18. Wenn die Strategien "immer kooperieren" und "immer defektieren" in
    einem evolutionären Gefangenendilemma gegeneinander antreten, welche
    Strategie setzt sich durch?

19. Was ist die Tit-for-Tat-Strategie?

20. Kann sich Tit-for-Tat immer durchsetzen?

21. Inwiefern ist "immer kooperieren" gefährlich für
    Tit-for-Tat-Spieler?

22. Was ist Governance?

23. Was ist Global Governance?

24. Was unterscheidet Governance von Regieren und von Management?

25. Was ist alles mit "global" in Gloabal Governance gemeint?

26. Wodurch ist Globalsisierung gekennzeichnet?

27. Welche Tendenzen sehen Sie gegenwärtig im Innen- und Außenverhältnis
    von Staaten?

28. Nehmen Sie Stellung zu der These, dass demokratische Rechtsstaaten
    nur mit anderen demokratischen Rechtsstaaten kooperieren sollten.

29. Inwiefern können interne Institutionen internationale Kooperation
    positiv oder negativ beeinflussen?

30. Inwiefern können Verteidigungsgemeinschaften wie die NATO Probleme
    mit Freifahrerverhalten haben?

------------------------------------------------------------------------

## Neue Fragen Sommersemester 2026 {.unnumbered}

1.  Was wird in der Außenhandelsökonomik mit Handelsoffenheit gemeint?

1.  Wie unterscheidet sich die Handelsoffenheit beispielsweise von
    Deutschland und den Vereinigten Staaten von Amerika voneinander?

1.  Was heißt das für Phänomene wie „Globalisierung“?

1.  Noch einmal zum Hillman-Modell: Welchen Vergleich müssen die Starken
    durchführen, wenn sie entscheiden wollen, ob sie den befriedeten
    Zustand akzeptieren/fortführen möchten oder nicht.

1.  Wodurch zeichnen sich die folgenden Kooperationsmodelle nach
    @patrick_rules_2023 aus: Charter-Modell, Club-Modell, Konzert-Modell
    und Koalitionen-Modell?

1. Charakterisieren Sie grob die internationale Migrationslage


1. Wer ist durch die Genfer Flüchtlingskonvention geschützt?

1. Worauf erstreckt sich der Schutzanspruch?

1. Wer hat Anspruch auf Asyl gemäß Art. 16a GG?

1. Welche Risiken und welche Chancen sind für die Europäische Union mit dem aktuellen außenpolitischen Politikwechsel der Vereinigten Staaten von Amerika verbunden?